### PR TITLE
fix: gitlab release creation

### LINKED ISSUE #204: GitLabError: Release notes modification via tags API is deprecated, see https://gitlab.com/gitlab-org/gitlab/-/issues/290311 (400)
Just running:

```bash
npx conventional-gitlab-releaser -p angular
```

as usual.

### PR DESCRIPTION
**Pull request by oroce**
Creating release on `repository/tags` endpoint has been deprecated and marked for removal on gitlab.
This causes non-zero exit codes, therefore, breaking automatic CI pipelines.

Fixes #204

ps: I removed the `Release ` prefix, I think it wasn't used previously (at least I haven't seen it in our projects where a couple of hundreds of releases were created by this module).

update: I had to remove `packages/conventional-tidelift-releaser/changelog.md` (not to be confused with CHANGELOG.md), which was empty file I guess accidentally pushed, but the default OSX file system is case insensitive)

### CODE REVIEW

File: packages/conventional-gitlab-releaser/src/index.js [hunk 1]
```diff
@@ -73,14 +73,14 @@ function conventionalGitlabReleaser (auth, changelogOpts, context, gitRawCommits
             return
           }
 
-          const url = `projects/${escape(context.owner + `/` + context.repository)}/repository/tags`
+          const url = `projects/${escape(context.owner + `/` + context.repository)}/releases`
```
Comment (oroce) [inline packages/conventional-gitlab-releaser/src/index.js:76]: API docs: https://docs.gitlab.com/ee/api/releases/#create-a-release

**Comment by oroce** [comment]
@hutson could you take a look at this?

Due to the Gitlab API deprecation, this issue became a blocker for us, we have to manually tag new releases since then.

**Comment by hutson** [comment]
@oroce generally this change looks good.

I do have a few requests if you would be willing to make a few changes:
- Squash all commits down into one.
- Add a `BREAKING CHANGE:` footer according to Conventional Commits (https://www.conventionalcommits.org/en/v1.0.0/#summary)
- Include in the breaking change section the minimum version of GitLab that is required.
- Update the GitLab `readme.md` with the new required version - https://github.com/conventional-changelog/releaser-tools/tree/master/packages/conventional-gitlab-releaser#required-gitlab-ceee-edition

Since this Pull Request changes the API end-point, and increases the minimum version of GitLab required, I will need to release the change as a new major version.

**Comment by oroce** [comment]
@hutson thanks for the detailed list, I did all of them.

To be honest the tidelift `CHANGELOG.md` and `changelog.md` issue on mac caused some issues to be able to rebase the commits.

At the end I had to delete both of the CHANGELOGs. The cleanest solution would be 
- either resolve that issue in master and then rebase this PR
- merge this PR then regenerate the tidelift changelog in master

Please let me know if I can help.

**Comment by hutson** [comment]
> either resolve that issue in master and then rebase this PR

I removed the `changelog.md` file from the default branch.

Can you rebase please? 

At that point I believe we can get this merged and released.

**Comment by oroce** [comment]
Thanks a lot. I rebased. 
The PR should be clean now.

**Comment by hutson** [comment]
@conventional-changelog/releaser-tools I do not have access to the npm packages to publish new versions. Can one of you please run `npm run release` to publish new versions with the changes from this pull request?

Here's what you should see:

```
> lerna publish --conventional-commits -m 'chore(release): publish'

lerna info version 2.11.0
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with conventional-github-releaser@3.1.5.
lerna info Checking for prereleased packages...

Changes:
 - conventional-gitlab-releaser: 4.0.3 => 5.0.0
 - conventional-tidelift-releaser: 1.0.2 => 1.0.3
```

**Comment by treyshedrick** [comment]
Is there an ETA on when the npm package will be published?
