### PR TITLE
Fix/update way to pass minimist options to meow 4

### LINKED ISSUE #63: Upgrade to meow ^4.0.0 breaks commands using the aliases
Hi there,

when upgrading to meow ^4.0.0 on commit 8f120c99753bd6002e0788b5c71e63864719d6a5, the usage of the aliases on conventional-github-releaseer got broken. We have to use --token instead of -t, or --config instead of -n. 

The release notes of https://github.com/sindresorhus/meow/releases warn on the way minimist options need to be passed for version ^4.0.0.

I have created https://github.com/conventional-changelog/releaser-tools/pull/62 that solves the issue. On top of it, the second commit adds the types of the flags as recommended in meow's README. I haven't created test because src/cli.js is explicitly excluded from them.

By the way @hbetts, out of interest, why is that you mention using `yarn` in the contributing if you are using package-lock.json? I have used `npm` because of the existence of package-lock.json. The links to the GitHub repo for issues and PRs read `GitLab`, as another small thing to correct in the CONTRIBUTING.md

The tests initially did not run, because I'm in GMT+2 and the line `chunk.committerDate = dateFormat(chunk.committerDate, 'yyyy-mm-dd', true)` in the transform.js, for both GitHub and GitLab, the 8th of June at 00:00 gets transformed to 7th June at 22:00 I guess?

Please let me know any feedback.

### PR DESCRIPTION
**Pull request by carlosvillademor**
The first commit is the one that fixes the issue where trying to use `flags.token` will have undefined value if the token was passed using the alias `-t`. The second commit is a recommendation from meow@4.0.0 documentation. The addition of default values is optional. 

This fixes #63.

### CODE REVIEW

File: packages/conventional-gitlab-releaser/src/cli.js [hunk 1]
```diff
@@ -35,17 +35,43 @@ const cli = meow({
...
-    k: 'pkg',
-    r: 'releaseCount',
-    v: 'verbose',
-    n: 'config',
-    c: 'context'
+  `,
+  flags: {
+    url: {
+      alias: 'u',
+      default: 'https://api.github.com',
```
Comment (hbetts) [inline packages/conventional-gitlab-releaser/src/cli.js]: I think this should be the GitLab API end-point.

Comment (carlosvillademor) [reply packages/conventional-gitlab-releaser/src/cli.js]: Copy and paste messed up, sorry about that, updated now @hbetts

**Comment by hbetts** [comment]
@carlosvillademor, I'm sorry for taking so long to get back to you on your change.

I really like the updates you've made.

I did notice that lower in the CLI files, specifically for GitLab, `url` is set to `flags.url || process.env.CONVENTIONAL_GITLAB_URL || 'https://gitlab.com',`.

Since the value of `flags.url` is now set to a default value, that particular line no longer has any effect. `flags.url` will always have a value. As a result, if someone sets `CONVENTIONAL_GITLAB_URL`, their environment variable wouldn't be used.

What do you think of getting rid of the environment variables and the default strings that come after them (At least for the GitLab CLI file), and then marking your commit as a breaking change?

**Comment by carlosvillademor** [comment]
Hi @hbetts , to be honest, I didn't realise about that. It is similar for the GitHub `url`, it gets set like `url: flags.url || process.env.CONVENTIONAL_GITHUB_URL`.

If you're happy removing the use of the environment variables and making this a breaking change, I'd be ok with it. But this would make people upgrading to this new version, and currently using the environment variables, to update their code. I am not sure whether it's worth it, to be honest, as I said in the PR description, the commit for the default values are optional. 

Now that I see the possible issue with setting the default urls, I think I wouldn't bump a new major for this.

I can update the PR to not set the default urls and update the code where the defaults are added to make sure they are handled in the same way.

**Comment by hbetts** [comment]
> I can update the PR to not set the default urls and update the code where the defaults are added to make sure they are handled in the same way.

Alright. That sounds fine with me. Let's go with that approach. :+1:
